### PR TITLE
Suricataのインストール方法を変更

### PR DESCRIPTION
**Pull request by takuma0121**
ソースからではなく、`apt-get`でインストールする方法に変更

### CODE REVIEW

**Comment by takuma0121** [comment]
root@eb1a1d047bf6:/home/work# rm current_version
root@eb1a1d047bf6:/home/work# cd -
/opt/ot_tools
root@eb1a1d047bf6:/opt/ot_tools# ./suricata_update.sh
--2022-03-23 14:32:37--  https://rules.emergingthreats.net/open/suricata-6.0.4/version.txt
Connecting to 10.146.1.35:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 5 [text/plain]
Saving to: 'version.txt'

version.txt              100%[================================>]       5  --.-KB/s    in 0s

2022-03-23 14:32:38 (98.5 KB/s) - 'version.txt' saved [5/5]

--2022-03-23 14:32:38--  https://rules.emergingthreats.net/open/suricata-6.0.4/emerging.rules.tar.gz
Connecting to 10.146.1.35:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 3211072 (3.1M) [application/octet-stream]
Saving to: 'emerging.rules.tar.gz'

emerging.rules.tar.gz    100%[================================>]   3.06M   934KB/s    in 3.4s

2022-03-23 14:32:42 (934 KB/s) - 'emerging.rules.tar.gz' saved [3211072/3211072]

--2022-03-23 14:32:42--  https://rules.emergingthreats.net/open/suricata-6.0.4/emerging.rules.tar.gz.md5
Connecting to 10.146.1.35:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 33 [text/plain]
Saving to: 'STDOUT'

-                        100%[================================>]      33  --.-KB/s    in 0s

2022-03-23 14:32:43 (3.85 MB/s) - written to stdout [33/33]

**Comment by takuma0121** [comment]
root@eb1a1d047bf6:/opt/ot_tools# suricata -c /opt/ot_tools/suricata.yaml -T
23/3/2022 -- 14:31:53 - <Info> - Running suricata under test mode
23/3/2022 -- 14:31:53 - <Notice> - This is Suricata version 6.0.4 RELEASE running in SYSTEM mode
23/3/2022 -- 14:32:10 - <Notice> - Configuration provided was successfully loaded. Exiting.
root@eb1a1d047bf6:/opt/ot_tools#

**Comment by takuma0121** [comment]
root@eb1a1d047bf6:/opt/ot_tools# suricata -V
This is Suricata version 6.0.4 RELEASE

**Comment by takuma0121** [comment]
root@eb1a1d047bf6:/opt/ot_tools# ./suricata_update.sh
--2022-03-23 14:31:00--  https://rules.emergingthreats.net/open/suricata-6.0.4/version.txt
Connecting to 10.146.1.35:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 5 [text/plain]
Saving to: 'version.txt'

version.txt              100%[================================>]       5  --.-KB/s    in 0s

2022-03-23 14:31:01 (469 KB/s) - 'version.txt' saved [5/5]

**Review by krk09 — APPROVED** [review]

**Pull request merged**
